services:
  - type: web
    name: prognoze
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: toto
          property: connectionString

